drop table account;
CREATE TABLE account (
  ID  INT  NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(30) DEFAULT NULL,
  MONEY DOUBLE DEFAULT NULL,
  CREATE_DATE TIMESTAMP DEFAULT NULL DEFAULT NOW(),
  PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;





